name: reddit
environment:
  sdk: ">=2.0.0 <3.0.0"

description: A Reddit library for Dart.
version: 0.5.0
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-reddit
dependencies:
  http: ">=0.11.1+3 <0.12.0"
  logging: ">=0.11.0 <0.12.0"
  oauth2: ">=1.0.1 <2.0.0"
dev_dependencies:
  test: ^1.5.1+1
